---
- hosts: localhost
  vars:
    source_key: "{{ playbook_dir }}/files/ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    terminal_emulator: "alacritty"
  pre_tasks:
    - include_tasks: tasks/dnf-configuration.yml
      when: ansible_distribution in ["Fedora"]
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core-setup.yml
      when: ansible_distribution in ["Fedora"]
    - include_tasks: tasks/core-packages.yml
      when: ansible_distribution in ["Fedora"]
    - include_tasks: tasks/node-setup.yml
    - include_tasks: tasks/npm-packages.yml
    - include_tasks: tasks/rust-setup.yml
    - include_tasks: tasks/docker-setup.yml
    # - include_tasks: tasks/nvim-setup.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/flatpak.yml
    # - include_tasks: tasks/fonts.yml
    # - include_tasks: tasks/gnome-settings.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/moonlander.yml
    - include_tasks: tasks/music-production.yml
    - include_tasks: tasks/tuning.yml
    - include_tasks: tasks/cleanup.yml
      when: ansible_distribution in ["Fedora"]
