- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    node_version: "16.17.1"
    rust_version: "1.64.0"
  pre_tasks:
    - include_tasks: tasks/dnf-configuration.yml
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/core-packages.yml
    - include_tasks: tasks/asdf-setup.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/cleanup.yml
