- hosts: localhost
  vars:
    source_key: "{{ playbook_dir }}/.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh-test/id_rsa"
  pre_tasks:
    - include_tasks: tasks/dnf-configuration.yml
  tasks:
    # temporarily disable until I can figure out how to test in docker
    # - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/core-packages.yml
    - include_tasks: tasks/node-setup.yml
    - include_tasks: tasks/npm-packages.yml
    - include_tasks: tasks/rust-setup.yml
    - include_tasks: tasks/flatpak.yml
    - include_tasks: tasks/docker-setup.yml
    - include_tasks: tasks/neovim.yml
    - include_tasks: tasks/music-production.yml
    - include_tasks: tasks/moonlander.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/tuning.yml
    # - include_tasks: tasks/fonts.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/cleanup.yml
