- name: install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.10.2
  tags:
    - install
    - asdf
- name: add node asdf plugin
  become: true
  shell: "{{ lookup('env', 'HOME') }}/.asdf/bin/asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git"
  tags:
    - install
    - asdf
    - node
- name: install correct node version
  become: true
  shell: "{{ lookup('env', 'HOME') }}/.asdf/bin/asdf install nodejs {{ node_version }}"
  tags:
    - install
    - asdf
    - node
- name: add rust asdf plugin
  become: true
  shell: "{{ lookup('env', 'HOME') }}/.asdf/bin/asdf plugin add rust https://github.com/asdf-community/asdf-rust.git"
  tags:
    - install
    - asdf
    - rust
- name: install correct rust version
  become: true
  shell: "{{ lookup('env', 'HOME') }}/.asdf/bin/asdf install rust {{ rust_version }}"
  tags:
    - install
    - asdf
    - rust
