---
- name: bottom | install | add copr repo
  tags: install,bottom
  become: true
  community.general.copr:
    state: enabled
    name: atim/bottom
- name: bottom | install | dnf package
  tags: install,bottom
  become: true
  dnf:
    name: bottom

