---
- name: bottom | install | snap application install
  tags: install,bottom
  become: true
  community.general.snap:
    name:
      - bottom
- name: bottom | configuration | provide correct snap access
  tags: install,bottom
  become: true
  command: sudo snap connect bottom:mount-observe && sudo snap connect bottom:hardware-observe && sudo snap connect bottom:system-observe &&  sudo snap connect bottom:process-control

