---
- name: brave | config | add brave repo
  tags: install,brave
  become: true
  command: 'dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/'
- name: brave | config | import rpm
  tags: install,brave
  become: true
  command: 'rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc'
- name: brave | install | dnf package
  tags: install,brave
  become: true
  dnf:
    name: brave-browser
- name: brave | extensions | create extensions directory
  tags: install,brave,extensions
  become: true
  command: mkdir -p /usr/share/chromium/extensions
- name: brave | extensions | copy extension files
  tags: install,brave,extensions
  become: true
  copy:
    src: '{{ playbook_dir }}/files/extensions/'
    dest: '/usr/share/chromium/extensions/'
    mode: 0644
