---
- name: system | cleanup | remove unwanted packages
  become: true
  dnf:
    name:
      - firefox
      - cheese
      - libreoffice*
      - rhythmbox
    state: absent
- name: system | cleanup | autoremove unneeded dependencies
  become: true
  dnf:
    autoremove: true
- name: system | cleanup | clean leftover dnf files
  become: true
  shell: dnf clean all
