- name: core | dnf | update cache
  become: true
  dnf:
    update_cache: true
- name: core | dnf | upgrade all packages
  become: true
  dnf:
    name: '*'
    state: latest
- name: core | dnf | groupupdate core packages
  become: true
  # ansible builtin command not available
  command: dnf groupupdate core -y
