---
# - name: core packages | install
#   tags: install,libraries
#   become: true
#   apt:
#     name:
#       - cmake
#       - libsecret
#       - pip
#       - webkit2gtk3-devel.x86_64
#       - openssl-devel
#       - curl
#       - wget
#       - libappindicator-gtk3
#       - librsvg2-devel
#       - dconf
#       - dbus-daemon
#       - fwupd
# - name: corepackages | install | development tools
#   tags: install,development
#   become: true
#   apt:
#     name: '@Development tools'
# - name: core packages | install | clang development tools
#   tags: install,development
#   become: true
#   apt:
#     name: '@C Development Tools and Libraries'
# - name: core packages | install | python dependencies
#   tags: install,python
#   become: true
#   command: pip install psutil --no-input --quiet
- name: core packages | install | essential user packages
  tags: install,terminal
  become: true
  apt:
    name:
      - exa # modern ls replacement
      - fzf # fuzzy finder
      - fd-find # modern find replacement (works with fzf)
      - ripgrep # much faster grep searching (works with fzf)
      - bat # modern cat replacement with syntax highlighting
      - tldr # minimal manual information
      - tmux # terminal window management utility
      - alacritty # GPU-based terminal editor
      - jq # modern json handling
      - gh # github cli
      - lsof
      - git-delta # better git diff
      - cronie # cron jobs
      - stow # managed symlinks
      - neofetch # system information
      - ncdu # disk usage management utility
      - wireshark # network monitoring utility
      - bleachbit # system cleaning utility
      - discord # chat application
      - vlc # always good to have a media player and codecs
      - shfmt # shell formatter for nvim null-ls package
