---
- name: dnf | config | add free rpm fusion repository
  tags: install,dnf
  become: true
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-37.noarch.rpm
    disable_gpg_check: true
- name: dnf | config | add  non-free rpm fusion repository
  tags: install,dnf
  become: true
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-37.noarch.rpm
    disable_gpg_check: true
- name: dnf | config | set fastestmirror
  tags: install,dnf
  become: true
  lineinfile:
    dest: '/etc/dnf/dnf.conf'
    create: true
    state: present
    line: 'fastestmirror=true'
    regexp: 'fastestmirror'
- name: dnf | config | set deltarpm
  tags: install,dnf
  become: true
  lineinfile:
    dest: '/etc/dnf/dnf.conf'
    create: true
    state: present
    line: 'deltarpm=true'
    regexp: 'deltarpm'
- name: dnf | config | set max_parallel_downloads
  tags: install,dnf
  become: true
  lineinfile:
    dest: '/etc/dnf/dnf.conf'
    create: true
    state: present
    line: 'max_parallel_downloads=10'
    regexp: 'max_parallel_downloads'
