---
- name: docker | install | add repo configuration
  become: true
  command: 'dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo'
- name: docker | install | dnf packages
  become: true
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
      - docker-compose-plugin
- name: docker | setup | enable rootless
  become: true
  command: "dockerd-rootless-setuptool.sh install"
- name: docker | setup | start docker service on boot
  become: true
  command: systemctl enable docker.service
- name: start containerd service on boot
  become: true
  command: "loginctl enable-linger jeffreylouden"
- name: add current user to docker group
  become: true
  shell: 'usermod -aG docker $USER'
