---
- name: dotfiles | install | stow
  become: true
  dnf:
    name: stow
  tags: install,dotfiles,stow
- name: dotfiles | install | clone .dotfiles repository
  git:
    repo: 'git@github.com:jeffreylouden/.dotfiles.git'
    dest: '~/.dotfiles'
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags: install,dotfiles,stow
- name: dotfiles | stow | run installation script
  shell: "cd ~/.dotfiles && ./install.sh"
  environment:
    STOW_FOLDERS: "alacritty,bat,bin,editorconfig,git,nvim,prettier,tmux,zsh"
  tags: install,dotfiles,stow
