- name: dotfiles | install | stow
  become: true
  dnf:
    name: stow
  tags: install,dotfiles,stow
- name: dotfiles | install | clone .dotfiles repository
  git:
    repo: 'git@github.com:jeffreylouden/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags: install,dotfiles,stow
- name: dotfiles | stow | create dotfile symlinks
  shell: |
    "cd {{ lookup('env', 'HOME') }}/.dotfiles"
    "./install.sh"
  tags: install,dotfiles,stow
