---
- name: dotfiles | install | clone .dotfiles repository
  tags: install,dotfiles,stow
  git:
    repo: 'git@github.com:jeffreylouden/.dotfiles.git'
    dest: '~/.dotfiles'
    recursive: true
    update: true
    accept_hostkey: true
    version: main
- name: dotfiles | stow | run installation script
  tags: install,dotfiles,stow
  shell: 'cd ~/.dotfiles && ./install.sh'
  environment:
    STOW_FOLDERS: 'alacritty,bat,bin,editorconfig,git,nvim,prettier,tmux,zsh'
