- name: Installing stow
  dnf:
    name: stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  git:
    repo: "git@github.com:jeffreylouden/.dotfiles.git"
    dest: "{{ ansible_user_dir }}/.dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  command: "{{ ansible_user_dir }}/.dotfiles"
  tags:
    - install
    - dotfiles
    - stow
