---
- name: flatpak | install | flatpak core
  become: true
  dnf:
    name: flatpak
- name: flathub flatpak repo
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
