---
- name: flatpak | update | post-repair update flatpak
  tags: install,flatpak
  become: true
  command: flatpak update
- name: flatpak | install | install packages
  community.general.flatpak:
    name:
      - "com.bitwig.BitwigStudio"
      - "com.discordapp.Discord"

