---
- name: flatpak | install | flatpak core
  become: true
  dnf:
    name:
      - flatpak
- name: flathub flatpak repo
  become: yes
  command: "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
- name: flatpak | install | repair flatpak installation
  become: true
  command: flatpak repair --user
- name: flatpak | update | post-repair update flatpak
  become: true
  command: flatpak update
