- name: flatpak | install | flatpak core
  become: true
  dnf:
    name: flatpak
- name: flatpak | config | add flathub remote
  become: true
  command: 'flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo'
