- name: install flatpak
  become: true
  dnf:
    name: flatpak
- name: add flathub remote
  become: true
  command: "flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo"
- name: install brave flatpak application
  become: true
  command: "flatpak install flathub com.brave.Browser --noninteractive"
- name: install discord flatpak application
  become: true
  command: "flatpak install flathub com.discordapp.Discord --noninteractive"
