- name: fonts | install | Dank Mono Regular
  copy:
    src: '{{ playbook_dir }}/files/fonts/DankMono-Regular.otf'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/DankMono-Regular.otf"
    mode: 0644
