- name: fonts | config | ensure fonts directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/dank-mono"
    mode: 700
    state: directory
- name: fonts | install | Dank Mono Regular
  copy:
    src: '{{ playbook_dir }}/files/fonts/DankMono-Regular.otf'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/dank-mono/DankMono-Regular.otf"
    mode: 0644
    decrypt: true
- name: fonts | install | Dank Mono Italic
  copy:
    src: '{{ playbook_dir }}/files/fonts/DankMono-Italic.otf'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/dank-mono/DankMono-Italic.otf"
    mode: 0644
    decrypt: true
- name: fonts | install | Dank Mono Bold
  copy:
    src: '{{ playbook_dir }}/files/fonts/DankMono-Bolde.otf'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/dank-mono/DankMono-Bold.otf"
    mode: 0644
    decrypt: true
- name: fonts | install | Dank Mono Italic Nerd Font Mono
  copy:
    src: '{{ playbook_dir }}/files/fonts/Dank\ Mono\ Italic\ Nerd\ Font\ Mono.otf'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts/dank-mono/Dank\ Mono\ Italic\ Nerd\ Font\ Mono.otf"
    mode: 0644
    decrypt: true
- name: font | cache | reset font cache
  become: true
  command: fc-cache
