---
- name: hosts | config | add raspberry pi zero entry
  tags: install,hosts
  become: true
  lineinfile:
    dest: '/etc/hosts'
    create: true
    state: present
    line: '192.168.86.99 pi.hole'
    regexp: 'pi.hole'
- name: hosts | config | add raspberry pi 4 entry
  tags: install,hosts
  become: true
  lineinfile:
    dest: '/etc/hosts'
    create: true
    state: present
    line: '192.168.86.247 pi.local'
    regexp: 'pi.local'
