---
- name: lazydocker | install | add copr repo
  tags: install,docker,lazydocker
  become: true
  community.general.copr:
    state: enabled
    name: atim/lazydocker
- name: lazydocker | install | apt package
  tags: install,docker,lazydocker
  become: true
  apt:
    name: lazydocker
