---
- name: lazygit | install | add copr repo
  tags: install,git,lazygit
  become: true
  community.general.copr:
    state: enabled
    name: atim/lazygit
- name: lazygit | install | dnf package
  tags: install,git,lazygit
  become: true
  dnf:
    name: lazygit
