---
- name: lazydocker | install | add copr repo
  become: true
  community.general.copr:
    state: enabled
    name: atim/lazydocker
- name: lazydocker | install | dnf package
  become: true
  dnf:
    name: lazydocker
