- name: Install nodejs and npm
  become: true
  dnf:
    name:
      - "nodejs"
      - "npm"
  tags:
    - install
    - node
- name: npmjs prefix
  command: mkdir -p "{{ ansible_user_dir }}/.local/.npm-global"
  tags:
    - install
    - node
- name: npmjs global settings
  command: npm config set prefix '{{ ansible_user_dir }}/.local/.npm-global'
  tags:
    - install
    - node
- name: Install N node manager
  npm:
    name: n
    global: true
  environment:
    PATH: "{{ ansible_user_dir }}/.local/.npm-global/bin:{{ ansible_env.PATH }}"
  tags:
    - install
    - node
- name: Install correct version of Node
  become: true
  command: n 16
  environment:
    PATH: "{{ ansible_user_dir }}/.local/.npm-global/bin:{{ ansible_env.PATH }}"
  tags:
    - install
    - node
