- name: Install nodejs and npm
  become: true
  ansible.builtin.dnf:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node
- name: npmjs prefix
  shell: mkdir -p ~/.local/.npm-global
  tags:
    - install
    - node
    - npm-path
- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags:
    - install
    - node
    - npm-path
- name: Install N
  npm:
    name: n
    global: true
  tags:
    - install
    - node
- name: Install correct version of Node
  become: true
  shell: n 16
  environment: # set explicit PATH override since dotfiles don't exist yet
    PATH: "{{ lookup('env', 'HOME') }}/.local/.npm-global/bin:{{ ansible_env.PATH }}"
  tags:
    - install
    - node
