---
- name: node | install | nodejs and npm
  tags: install,node
  become: true
  dnf:
    name:
      - 'nodejs'
      - 'npm'
- name: node | config | create npmjs prefix directory
  tags: install,node
  command: mkdir -p "{{ lookup('env', 'HOME') }}/.local/.npm-global"
- name: node | config | set npmjs global prefix
  tags: install,node
  command: npm config set prefix "{{ lookup('env', 'HOME') }}/.local/.npm-global"
- name: node | install | n node manager
  tags: install,node
  npm:
    name: n
    global: true
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/.npm-global/bin:{{ ansible_env.PATH }}"
- name: node | install | node 16
  tags: install,node
  become: true
  command: n 16
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/.npm-global/bin:{{ ansible_env.PATH }}"
