- name: neovim | install | apt package
  tags: install,libraries,neovim
  become: true
  apt:
    name:
      - neovim
      - python3-neovim
- name: neovim | install | npm package
  tags: install,node,neovim
  npm:
    name: neovim
    global: true

