- name: neovim | install | install neovim
  become: true
  dnf:
    name:
      - neovim
      - python3-neovim
  tags: install,libraries,neovim
- name: install neovim
  npm:
    name: neovim
    global: true
  tags: install,node,neovim
