- name: neovim | install | dnf package
  tags: install,libraries,neovim
  become: true
  dnf:
    name:
      - neovim
      - python3-neovim
- name: neovim | install | npm package
  tags: install,node,neovim
  npm:
    name: neovim
    global: true

