- name: neovim | install | dnf package
  tags: install,libraries,neovim
  become: true
  dnf:
    name:
      - neovim
      - python3-neovim
- name: neovim | install | npm package
  tags: install,node,neovim
  npm:
    name: neovim
    global: true
- name: neovim | install | LunarVim
  tags: install,neovim,lunarvim
  command: "LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh -y --install-dependencies)"
