- name: neovim | install | dnf package
  become: true
  dnf:
    name:
      - neovim
      - python3-neovim
  tags: install,libraries,neovim
- name: neovim | install | npm package
  npm:
    name: neovim
    global: true
  tags: install,node,neovim
