---
- name: rust | config | check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true
  tags: install,rust
- name: rust | install | download cargo installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags: install,rust
- name: rust | install | rust and cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags: install,rust
