- name: ensure .ssh directory exists
  become: true
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: install private ssh key
  become: true
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
    remote_src: true # https://github.com/ansible/ansible/issues/2303
  tags:
    - dotfiles
    - install
    - ssh
- name: install ssh key public
  become: true
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
    remote_src: true # https://github.com/ansible/ansible/issues/2303
  tags:
    - dotfiles
    - install
    - ssh
- name: set authorized key took from file
  become: true
  authorized_key:
    user: jeffreylouden
    state: present
    key: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
  with_fileglob:
    - "{{ ansible_user_dir }}/.ssh/*.pub"
