- name: ssh | config | ensure .ssh directory exists
  file:
    dest: '{{ dest_key | dirname }}'
    mode: 0700
    state: directory
  tags: dotfiles,install,ssh
- name: ssh | install | private ssh key
  copy:
    src: '{{ source_key }}'
    dest: '{{ dest_key }}'
    mode: 0600
    decrypt: true
  tags: dotfiles,install,ssh
- name: ssh | install | public ssh key
  copy:
    src: '{{ source_key }}.pub'
    dest: '{{ dest_key }}.pub'
    mode: 0644
  tags: dotfiles,install,ssh
- name: ssh | config | set authorized key
  authorized_key:
    user: jeffreylouden
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
- name: ssh | config | ensure github.com is a known host
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
    create: true
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
