- name: gnome | appearance | copy wallpaper file
  tags: gnome,gnome-wallpaper
  copy:
    src: '{{ playbook_dir }}/files/wallpapers/wallpaper.jpg'
    dest: "{{ lookup('env', 'HOME') }}/wallpaper.jpg"
    mode: 0644
- name: gnome | appearance | set wallpaper
  tags: gnome,gnome-wallpaper
  gsetting:
    settings:
      org.gnome.desktop.background.picture-uri: "'file://{{ lookup('env', 'HOME') }}/wallpaper.jpg'"
      org.gnome.desktop.background.picture-uri-dark: "'file://{{ lookup('env', 'HOME') }}/wallpaper.jpg'"
      org.gnome.desktop.background.picture-options: "'zoom'"
