- name: gnome | appearance | copy wallpaper file
  tags: gnome,gnome-wallpaper
  copy:
    src: '{{ playbook_dir }}/files/wallpapers/flowers.jpg'
    dest: "{{ lookup('env', 'HOME') }}/flowers.jpg"
    mode: 0644
- name: gnome | appearance | set wallpaper
  tags: gnome,gnome-wallpaper
  dconf:
    key: '/org/gnome/desktop/background/picture-uri'
    value: "'file://{{ lookup('env', 'HOME') }}/flowers.jpg'"
- name: gnome | appearance | set wallpaper (dark)
  tags: gnome,gnome-wallpaper
  dconf:
    key: '/org/gnome/desktop/background/picture-uri-dark'
    value: "'file://{{ lookup('env', 'HOME') }}/flowers.jpg'"
- name: gnome | appearance | set wallpaper position
  tags: gnome,gnome-wallpaper
  dconf:
    key: '/org/gnome/desktop/background/picture-options'
    value: "'zoom'"
