- name: gnome | appearance | copy wallpaper file
  tags: gnome,gnome-wallpaper
  copy:
    src: "{{ playbook_dir }}/files/wallpapers/wallpaper.jpg"
    dest: /usr/share/backgrounds/wallpaper.jpg
    mode: 0644
- name: gnome | appearance | set wallpaper
  tags: gnome,gnome-wallpaper
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/wallpaper.jpg'"
- name: gnome | appearance | set wallpaper position
  tags: gnome,gnome-wallpaper
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'fill'"
  #- name: gnome | appearance | set shell theme
  #  become_user: jay
  #  dconf:
  #    key: "/org/gnome/shell/extensions/user-theme/name"
  #    value: "'Shades-of-gray'"
  #
  #
  #- name: gnome | appearance | gnome | appearance | set icon theme
  #  become_user: jay
  #  dconf:
  #    key: "/org/gnome/desktop/interface/icon-theme"
  #    value: "'Moka-Minimal'"
  #- name: gnome | appearance | set GTK theme
  #  become_user: jay
  #  dconf:
  #    key: "/org/gnome/desktop/interface/gtk-theme"
  #    value: "'Shades-of-gray'"
