# Enable Dark Mode
- name: gnome | shell settings | enable dark mode
  tags: gnome,gnome-shell
  gsetting:
    settings:
      org.gnome.desktop.interface.color-scheme: "'prefer-dark'"
      org.gnome.desktop.interface.enable-hot-corners: 'false'
      org.gnome.desktop.interface.clock-format: "'12h'"
      org.gnome.shell.favorite-apps: "['org.gnome.Nautilus.desktop', 'Alacritty.desktop', 'brave-browser.desktop', 'discord.desktop']"
      org.gnome.desktop.sound.event-sounds: 'false'
      org.gnome.desktop.sound.allow-volume-above-100-percent: 'true'
      org.gnome.desktop.session.idle-delay: 'uint32 0'
      org.gnome.desktop.sound.input-feedback-sounds: 'false'
      org.gnome.desktop.privacy.old-files-age: 'uint32 14'
      org.gnome.desktop.privacy.remove-old-temp-files: 'true'
      org.gnome.desktop.privacy.remove-old-trash-files: 'true'
      org.gnome.desktop.interface.show-battery-percentage: 'true'
      org.gnome.desktop.notifications.show-in-lock-screen: 'false'
      org.gnome.shell.overrides.workspaces-only-on-primary: 'true'
      # org.gtk.settings.file-chooser.show-hidden: 'true'
