---
- name: music production | install | media dependencies
  become: true
  dnf:
    name:
      - xz # utility to untar u-he plugins
      - kf5-kservice # KDE dependencies for reaper
      - tycmd # m8 firmware tool
      - libcurl # seemingly a dependency for Audio Assault plugins
- name: music production | config | add libcurl-gnutls copr repo
  tags: install,music,dependencies
  become: true
  community.general.copr:
    state: enabled
    name: patrickl/libcurl-gnutls
- name: music production | install | libcurl-gnutls package
  tags: install,music,dependencies
  become: true
  dnf:
    name: libcurl-gnutls
- name: music production | dependencies | start kbuildsycoca5
  tags: install,music,dependencies
  command: kbuildsycoca5
