---

- name: music production | plugins | download u-he MFM2 plugin
  tags: install, music, plugins
  shell: 'curl -L https://dl.u-he.com/releases/MFM2_25_13385_Linux.tar.xz | tar -xJ'
- name: music production | plugins | install u-he MFM2 plugin
  tags: install, music, plugins
  command: './MFM2-13385/install.sh --quiet' # TODO: brittle. can i somehow find the latest version?

- name: music production | plugins | download u-he Satin plugin
  tags: install, music, plugins
  shell: 'curl -L https://dl.u-he.com/releases/Satin_132_12092_Linux.tar.xz | tar -xJ'
- name: music production | plugins | install u-he Satin plugin
  tags: install, music, plugins
  command: './Satin-12092/install.sh --quiet' # TODO: brittle. can i somehow find the latest version?

- name: music production | plugins | download u-he Presswerk plugin
  tags: install, music, plugins
  shell: 'curl -L  https://dl.u-he.com/releases/Presswerk_115_12092_Linux.tar.xz | tar -xJ'
- name: music production | plugins | install u-he Presswerk plugin
  tags: install, music, plugins
  command: './Presswerk-12092/install.sh --quiet' # TODO: brittle. can i somehow find the latest version?

- name: music production | plugins | download u-he Diva plugin
  tags: install, music, plugins
  shell: 'curl -L  https://dl.u-he.com/releases/Diva_145_12092_Linux.tar.xz | tar -xJ'
- name: music production | plugins | install u-he Diva plugin
  tags: install, music, plugins
  command: './Diva-12092/install.sh --quiet' # TODO: brittle. can i somehow find the latest version?

- name: music production | plugins | download TAL Reverb
  tags: install, music, plugins
  command: 'wget "https://tal-software.com/downloads/plugins/TAL-Reverb-4_64_linux.zip"'
- name: music production | plugins | unzip TAL Reverb
  tags: install, music, plugins
  command: 'unzip -o TAL-Reverb-4_64_linux.zip -d TAL-Reverb/'
- name: music production | plugins | move TAL Reverb
  tags: install, music, plugins
  command: ' cp -r TAL-Reverb/TAL-Reverb-4.vst3 ~/.vst3'
# https://copr.fedorainfracloud.org/coprs/patrickl/wine-tkg-testing/
# https://copr.fedorainfracloud.org/coprs/patrickl/yabridge-stable/

