---
- name: music production | DAW | download reaper
  tags: install, music, reaper
  shell: 'curl -L https://www.reaper.fm/files/6.x/reaper669_linux_x86_64.tar.xz | tar -xJ'
- name: music production | DAW | install reaper
  tags: install, music, reaper
  become: true
  shell: './reaper_linux_x86_64/install-reaper.sh --quiet --install ~/opt --integrate-user-desktop'
- name: music production | reaper | install sws sws-extension
  tags: install, music, reaper
  shell: 'curl -L https://www.sws-extension.org/download/featured/sws-2.12.1.3-Linux-x86_64.tar.xz | tar -xJ -C ~/.config/REAPER'
- name: music production | reaper | download reaPack extensions
  tags: install, music, reaper, reapack, extensions
  command: 'wget https://github.com/cfillion/reapack/releases/download/v1.2.4.2/reaper_reapack-x86_64.so'
- name: music production | reaper | install reaPack extensions
  tags: install, music, reaper, reapack, extensions
  command: 'mv reaper_reapack-x86_64.so ~/.config/REAPER/UserPlugins'

