---
- name: music production | install | clone studio repository
  tags: install,music,reaper,stow
  git:
    repo: 'git@github.com:jeffreylouden/studio.git'
    dest: '~/.studio'
    recursive: true
    update: true
    accept_hostkey: true
    version: main

- name: music production | stow | run installation script
  tags: install,music,reaper,stow
  shell: 'cd ~/.studio && ./install.sh'

